services:
  ephemeral-chatter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: ephemeral-chatter
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  tor:
    image: goldy/tor-hidden-service
    container_name: tor
    links:
      - caddy
    environment:
      CADDY_HOST: caddy
      CADDY_PORTS: 80:80
    volumes:
      - ./tor-keys:/var/lib/tor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: